name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: ECHO
        run: |
            echo `python --version`
            echo `pip --version`
            pip install -r requirements.txt -t .
