name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    env:
      DD_SITE: datadoghq.com
      DD_API_KEY: ${{secrets.DD_API_KEY}}
      DD_APP_KEY: ${{secrets.DD_APP_KEY}}
    steps:
      - uses: actions/checkout@v3
      - name: ECHO
        run: |
            echo `python --version`
            echo `pip --version`
            pip install -r requirements.txt -t .
