name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
#     container:
#       image: datadog/dogstatsd:latest
#       env:
#         DD_API_KEY: ${{secrets.DD_API_KEY}}
#       options: --cgroupns host --pid host
    steps:
      - name: ECHO
        run: |
            echo `pwd`
            echo `ls -la`
