name: CI
on:
  push:
    branches: [ main ]
jobs:
  container-test-job:
    runs-on: ubuntu-latest
    container:
      image: datadog/dogstatsd:latest
      env:
        DD_API_KEY: ${{secrets.DD_API_KEY}}
      options: --cgroupns host --pid host
    steps:
      - uses: actions/checkout@v3
      - name: ECHO
        run: |
            echo `pwd`
            echo `ls -la`
